[window]
padding = { x = 2, y = 2}
class = { instance = "Alacritty", general = "Alacritty" }

[window.dimensions]
columns = 130 
lines = 35

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerd Font Mono", style = "BoldItalic" }

size = 13

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"
